language: ruby
sudo: false
services: postgresql
bundler_args: --without development --deployment
rvm:
  - 2.3.1
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
before_script:
  - cp -f config/travis/database.yml config/database.yml
  - bundle exec rake db:create db:migrate
script: bundle exec rspec --color
