# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa0bdec042b91cde172700278e9385fb9ad8061cd399262aa7e0908600a9d83764603c9251b6a1cc0f67cac7a92ba73bf13904bcaf8aa92f13b9b92b3caa46d

test:
  secret_key_base: 9bdf8af96a771991cd5ffb531f453100a16ff01593d8c0c4baeca8d4816e130de70e67240be63a2a2389e707217bdf7d7bd5cdfe617852e624ca23d353f01d43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
